### ISSUE TITLE
`int_in_range` for 1.1.4 now returning out of range values for 0..1i8

### ISSUE THREAD

**Issue by morphmeme** [rust-fuzz/arbitrary#119]
`int_in_range(0..=1i8)` is generating values from -1 to 1. It generates -1 less often than the others.

I tried reasoning about the latest code change, but couldn't figure it out.

It also generates negative numbers for `0..=i32::MAX` and `0..=i64::MAX`.

**Comment by Manishearth** [comment]
Ought to be fixed by https://github.com/rust-fuzz/arbitrary/pull/118

(we should cut a release)
