### ISSUE TITLE
int_in_range_impl can panic on valid ranges

### ISSUE THREAD

**Issue by kpreid** [rust-fuzz/arbitrary#120]
https://github.com/rust-fuzz/arbitrary/blob/a9c01d7a626c60d7eab9878ca3b21120c33b8350/src/unstructured.rs#L322

This line can panic if `end - start` doesn't fit in the range of the number type, such as if `start` is near `i32::MIN` and `end` is near `i32::MAX`.

I discovered this via my fuzzing in CI (which uses such ranges) starting to fail after the release of arbitrary 1.1.4 a few hours ago.

**Comment by Manishearth** [comment]
cc @fitzgen hmm

**Comment by Manishearth** [comment]
This probably broke because of https://github.com/rust-fuzz/arbitrary/pull/118
