### ISSUE TITLE
`arbitrary` v1.2.0 + `derive` doesn't build with `generate-lockfile -Z minimal-versions`

### ISSUE THREAD

**Issue by tarcieri** [rust-fuzz/arbitrary#134]
It pulls in `derive_arbitrary` v1.1.6 which has the following build failure:

```
error[E0599]: no method named `len` found for reference `&Fields` in the current scope
   --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/derive_arbitrary-1.1.6/src/lib.rs:219:30
    |
219 |         if idx + 1 == fields.len() {
    |                              ^^^ method not found in `&Fields`
```

Perhaps you could bump the `derive_arbitrary` requirement in `arbitrary` to `1.2.0` (it's presently `1.1.6`) or yank the affected `derive_arbitrary` v1.1.6 release?

**Comment by fitzgen** [comment]
@Manishearth FWIW, this kind of thing is the reason why I try to always keep the versions in lock step with each other.

**Comment by Manishearth** [comment]
Yeah, fair, I still think it should be fine for patches.
