### ISSUE TITLE
Add implementations for std types such as SocketAddr

### ISSUE THREAD

**Issue by howardjohn** [rust-fuzz/arbitrary#145]
`quickcheck::Arbitrary` has a bunch of implementations for common types such as [SocketAddr](https://docs.rs/quickcheck/latest/src/quickcheck/arbitrary.rs.html#494-498). However,  `arbitrary::Arbitrary` is a bit more restrictive. this means (I think) that anything that wants to derive Arbitrary needs to either manually write the trait impl or use a wrapper type

**Comment by nagisa** [comment]
Happy to accept pull requests as demand for specific types arises.
