### ISSUE TITLE
Arbitrary derive doesn't play nicely with cfg_attr

### ISSUE THREAD

**Issue by silvergasp** [rust-fuzz/arbitrary#149]
So I'm trying to keep the arbitrary crate as an optional dependency for a project. So I'd like to conditionally derive the arbitrary implementation e.g.
```rust
#[derive(Clone, Debug, Deserialize)]
#[cfg_attr(feature = "arbitrary", derive(arbitrary::Arbitrary))]
pub enum Number {
        Int(i64),
        Float(f64),
        Decimal(BigDecimal),
}
```
This works fine when every var/enum variant also implements derive (or I can implement it manually). However in this case `bigdecimal::BigDecimal` is in an external crate that I don't have control over so I'd like to be able to do something like this;
```rust
#[derive(Clone, Debug, Deserialize)]
#[cfg_attr(feature = "arbitrary", derive(arbitrary::Arbitrary))]
pub enum Number {
        Int(i64),
        Float(f64),
        #[cfg_attr(feature = "arbitrary", arbitrary(with = |u: &mut Unstructured| BigDecimal::from(u64::arbitrary(&mut u))))]
        Decimal(BigDecimal),
}
```
Where I conditionally enable lambda implementation for that variant type. However for whatever reason this doesn't actually work and I get an error like;
```
27 | #[cfg_attr(feature = "arbitrary", derive(arbitrary::Arbitrary))]
   |                                          ^^^^^^^^^^^^^^^^^^^^ the trait `Arbitrary<'_>` is not implemented for `BigDecimal`
```

**Comment by Manishearth** [comment]
Hm, that's strange, `cfg_attr` is handled by the compiler and the proc macro has no visibility of that in the first place.

**Comment by silvergasp** [comment]
Oh weird, perhaps it's just because it's an enum variant. To be honest I haven't tried using that attribute with an enum before, only structs. I'll investigate a little further.

**Comment by Manishearth** [comment]
Oh!

The attribute needs to be on the _field_, not the _variant_.

That explains that.

We should perhaps throw an error if you use `#[arbitrary(with)]` on a variant.

**Comment by Manishearth** [comment]
Closing as works-as-intended, but filed https://github.com/rust-fuzz/arbitrary/issues/150 for the diagnostics (and potentially making the case you laid out automatic)

Thanks for reporting!

**Comment by silvergasp** [comment]
No worries thanks for being so responsive!
