### ISSUE TITLE
Arbitrary has problems with generic structs

### ISSUE THREAD

**Issue by iirekm** [rust-fuzz/arbitrary#186]
For example:
```rust
trait Tr<'a> : Arbitrary<'a> {}

#[derive(Arbitrary)]
struct S<'a, T: Tr<'a>> {
    t: T
}
```

No matter how I try to fix it, I always get errors in expansion of this derive macro.

**Comment by fitzgen** [comment]
I don't have time to debug this for you right now, but fwiw here's our test for the derive macro with a generic type parameter:

https://github.com/rust-fuzz/arbitrary/blob/8fff98e73f91aa3ff9348f3fbd27a8f0546436bd/tests/derive.rs#L141-L155

We could certainly have better and more tests here.

If making your example look more like the test doesn't fix things for you, then the following would help improve your bug report:

* The full error(s) that `rustc` reports for your test case
* The output of `cargo expand` showing the code that the macro expanded to

**Comment by iirekm** [comment]
I found a workaround: avoid generics bounds on structs as much as possible (e.g. `T: Tr<'a>` in this example), and apply them only on traits. It's good enough for me.
