### ISSUE TITLE
Rename repo to `arbitrary`?

### ISSUE THREAD

**Issue by Manishearth** [rust-fuzz/arbitrary#22]
Doesn't make sense to duplicate rust in the title, especially with underscores.

**Comment by nagisa** [comment]
Originally it was `rust_` because I name my rust crates under my name that.

Makes perfect sense to rename to `arbitrary` now that its in `rust-fuzz` org.

**Comment by nagisa** [comment]
And… its done.

**Comment by fitzgen** [comment]
Nice.
