### ISSUE TITLE
Derive failing in v0.4.2

### ISSUE THREAD

**Issue by kirk-baird** [rust-fuzz/arbitrary#39]
# What is the issue

The derive macro seems to have build issues when called upon via the crate in version `0.4.2`

# Example 

Cargo.toml
```
[dependencies]
arbitrary = { version = "=0.4.2", features = ["derive"] }
```

main.rs
```rust
use arbitrary;

#[derive(arbitrary::Arbitrary)]
pub struct Wrapper {
    pub x: u8,
}

fn main() {
    let a = Wrapper {
        x: 3,
    };
    println!("{}", a.x);

```

# Version 0.4.1

This was working in v0.4.1 and can be seen by changing the Cargo.toml in the above example to 
```
arbitrary = { version = "=0.4.1", features = ["derive"] }
```
And re-running main.rs from above.

# libfuzzer-sys

I'm not sure the exact cause of the issue but it will impact `libfuzzer_sys v0.3.2` which 
re-exports `arbitrary::Arbitrary`

# Work around for `libfuzzer_sys v0.3.2`

I noticed there is a work around by doing 
Also have `arbitrary v0.4.2` as a dependency with `features = ["derive']`.
Then importing `Arbitrary` directly from `arbitrary`

e.g. for a fuzzer 

```
use libfuzzer_sys::fuzz_target;
use arbitrary::Arbitrary;
```

as opposed to how it would previously be done
```
use libfuzzer_sys::{fuzz_target, arbitrary::Arbitrary};
```

**Comment by Manishearth** [comment]
Fix seems to be https://github.com/rust-fuzz/arbitrary/pull/40

(for future reference, please include the error message you're seeing!)

**Comment by kirk-baird** [comment]
Excellent thanks for the quick resolution!

Oops yep forgot to include the error message, I'll be sure to add it next time.
