### ISSUE TITLE
Consider adding a lifetime parameter to Arbitrary

### ISSUE THREAD

**Issue by fitzgen** [rust-fuzz/arbitrary#43]
If we tweaked the `Arbitrary` definition into this:

```rust
pub trait Arbitrary<'a>: Sized {
    fn arbitrary(u: &mut Unstructured<'a>) -> Result<Self>;

    // ...
}
```

Then we would allow implementing `Arbitrary` for things that borrow from the input string:

```rust
struct HasBorrow<'a> {
    borrow: &'a [u8],
}

impl<'a> Arbitrary<'a> for HasBorrow<'a> {
    fn arbitrary(u: &mut Unstructured<'a>) -> arbitrary::Result<HasBorrow<'a>> {
        let size = u.arbitrary_byte_size()?;
        let borrow = u.get_bytes(size)?;
        Ok(HasBorrow { borrow })
    }
}
```

There are two concerns, off the top of my head:

1. This is a breaking change, and shouldn't be done lightly. Perhaps delayed until we have more breaking changes that we can roll up into one release.

2. Right now, `Arbitrary` requires that types that implement it be `'static` and I can't remember why. There sure are a bunch of errors when I remove this bound though. Anyways, this would also have to be removed.

**Comment by frewsxcv** [comment]
Done in https://github.com/rust-fuzz/arbitrary/pull/63

**Comment by yancyribbens** [comment]
Is there anything that can be done if the borrow is `&'a [u64]` for example?

```rust
struct HasBorrow<'a> {
    borrow: &'a [u64],
}
```

Since `bytes()` returns `&'a [u8]` this doesn't seem to work for other types.
