### ISSUE TITLE
Derive `Arbitrary` for types with lifetimes

### ISSUE THREAD

**Issue by mcy** [rust-fuzz/arbitrary#50]
`derive(Arbitrary)` currently won't derive `Arbitrary` if the type has a lifetime parameter in it. Most of the time this is fine, because `Arbitrary: 'static`. However, it seems like it would be possible to implement `Arbitrary` if all of the type parameters were set to `'static`. This is somewhat inconsistent with `Cow<'static, impl Arbitrary>: Arbitrary`.

I haven't looked into how hard this would be, but I'm willing to mail a change adding this (maybe behind a Cargo feature?) if maintainers would consider it a useful addition.

**Comment by fitzgen** [comment]
Yeah, if the lifetime is `'static` then the derive should handle it.

The derive's code is in `./derive/src/lib.rs`. I'm not sure off the top of my head what would need to change in there to support this.

**Comment by mcy** [comment]
I think I didn't phrase what I meant correctly. I want the following behavior:
```rust
#[derive(Arbitrary)]
struct Foo<'a, 'b, ...> { ... }
// Generated impl:
impl Arbitrary for Foo<'static, 'static, ...> { ... }
```
I believe that this should be "easy", by blindly rewriting every lifetime into `'static`. I would have liked to write
```rust
#[derive(Arbitrary)]
type StaticFoo = Foo<'static, 'static, ...>;
```
I feel this is less surprising syntax but not something proc macros can do AFAIK, since they don't have type information available.

**Comment by frewsxcv** [comment]
Done in https://github.com/rust-fuzz/arbitrary/pull/63
