### ISSUE TITLE
Replace arbitrary_array macro with const generics (after stabilization)

### ISSUE THREAD

**Issue by frewsxcv** [rust-fuzz/arbitrary#69]
https://github.com/rust-fuzz/arbitrary/blob/ab4adcf12045858148e93e70b85a93559ae6e214/src/lib.rs#L716-L797

**Comment by frewsxcv** [comment]
An attempt was made in https://github.com/rust-fuzz/arbitrary/pull/55

**Comment by e00E** [comment]
Maybe this can be closed because the PR was merged. Although no release with this feature has been made.
