### ISSUE TITLE
Implement an MSRV policy

### ISSUE THREAD

**Issue by djc** [rust-fuzz/arbitrary#99]
I noticed that this crate currently doesn't have an explicit minimum supported Rust version policy, nor does it check the MSRV in CI. With #98, this now depends on `ControlFlow`, which was introduced in Rust 1.55. I know many crates try to keep the MSRV to at least 6 months back, which would be 1.54 right now. (I'm using arbitrary for Quinn, which is currently checking for 1.53 support.) Since `ControlFlow` is now part of the public API for 1.x, I suppose reverting this change (or using a local copy of `ControlFlow`) is not a very attractive option for now, but it would be nice to put something in place to this at least gets noticed in the future.

**Comment by Manishearth** [comment]
Overall I'm not much in favor of making such a commitment; especially since the primary use case for `arbitrary` is for being used in fuzz environments and I see far less pressure to stick to an older rust version there.

I would recommend not including the `arbitrary` feature in your MSRV policy.

**Comment by fitzgen** [comment]
I'm inclined to agree with @Manishearth here.

**Comment by djc** [comment]
That's fair.
